### PR TITLE
🧱Working on EMAIL OTP system!

### PR DESCRIPTION
**Pull request by RyanBroemer**
- Fixes env for backend into the real groups.
- prod:api production env
- dev:api developing env
- test:api testing env

### CODE REVIEW

**Comment by RyanBroemer** [comment]
Someone from front end pls hop into this branch and make sure the front end code is correct.
for some reason the merge from develop to feature - API had conflicts but I only changed back-end.
I took all incoming changes from the most recent develop branch so I believe its up to date!

**Comment by DYL-WF** [comment]
dude you were supposed to add these  things to the CI/CD branch

**Comment by RyanBroemer** [comment]
What, why these are API related changes for using different databases?

**Comment by RyanBroemer** [comment]
Removed what was not meant to be uploaded. 
These are now only API changes the commands are still the same they will just be using the proper the env files in the future.

**Comment by DYL-WF** [comment]
why did you take the .env's our of the gitignore @RyanBroemer

**Comment by RyanBroemer** [comment]
Its better to do *.env so no envs from back-end are sent over to the repo because of the information in them.

**Comment by RyanBroemer** [comment]
Im busy implementing the OTP system now, will send the new stuff soon!

**Comment by RyanBroemer** [comment]
- Adding real email validation when inserting new users. 
- Checking valid emails before even trying to create new OTP or User.
- Preparing for nodemailer use!

**Comment by RyanBroemer** [comment]
- Adding email validation to employee insertions.
- Adding updated test for validation.

**Comment by RyanBroemer** [comment]
- Adding email validation to employee OTP request.
- Adding tests for the OTP email validation.

**Comment by RyanBroemer** [comment]
- Adding email validation to email insertions.
- Adding tests for the validation.

**Comment by RyanBroemer** [comment]
- Adding email validation for owner OTP.
- Adding testing for validation.

**Comment by RyanBroemer** [comment]
I think this should be merged so long, Ill finish the real email system either later tonight or tomorrow!

**Comment by RyanBroemer** [comment]
For some reason the DROP ALL tables API call on heroku was reimplemented and the create all tables was commented out.

**Comment by RyanBroemer** [comment]
- Full OTP system completed with API testing.
- Please approve but do no merge, will update the branch and merge later!!!

**Review by RobynHancock — APPROVED** [review]

**Pull request merged**
