### PR TITLE
Updated Login/Register

### PR DESCRIPTION
**Pull request by jademichellepeche**
Updated the API calls:
Login page should be able to login a user, employee and owner.
Register page registers a user.

### CODE REVIEW

**Comment by DYL-WF** [comment]
why are there two of these?

**Review by RyanBroemer — COMMENTED** [review]
Looks good

**Comment by RyanBroemer** [comment]
Its strange, they even hold the same git hex address.

**Comment by DYL-WF** [comment]
should we just close this one and merge the other?

**Comment by RyanBroemer** [comment]
Yes lets do that.

**Comment by RyanBroemer** [comment]
Closed this one so we merge other.

**Pull request closed without merging**
