### PR TITLE
Feature api social feature(back-end)

### PR DESCRIPTION
**Pull request by DYL-WF**
- implement the friend and subscription relations
 - implement the friend and subscription api calls

### CODE REVIEW

**Comment by RyanBroemer** [comment]
- Adding 5 minute timeouts to OTP created from the User, Employee and Owner OTPs.
- Branch is the latest update from @DYL-WF Work.
- It should not affect his code.

**Review by RyanBroemer — APPROVED** [review]
Looks good!, everything passes on develop env.
We will have to reset our entire DB to follow new schema!

**Comment by RyanBroemer** [comment]
The OTP calls and future gym brand table will fail now on production until we agree to reset DB!

**Comment by DYL-WF** [comment]
> The OTP calls and future gym brand table will fail now on production until we agree to reset DB!

i managed to get my tables in without resetting the DB

**Comment by RyanBroemer** [comment]
Inserting new tables is fine, updating existing tables is the problem!

**Pull request merged**
