### PR TITLE
Create Monorepo with front and backend

### PR DESCRIPTION
**Pull request by DYL-WF**
- created yarn monorepo
- added react app
- added express project

@AvinashSingh786 is this better ?

### CODE REVIEW

**Review by AvinashSingh786 — CHANGES_REQUESTED** [review]
Much better, but remove object files, like node_modules, or package libs, etc.

**Comment by DYL-WF** [comment]
@AvinashSingh786 im a little confused. are there any object files? are you reffering to the package folder?

**Comment by AvinashSingh786** [comment]
> @AvinashSingh786 im a little confused. are there any object files? are you reffering to the package folder?

It's typically a bad idea to commit node_modules folder and files that are generated by package managers as they won't work across all devices and sometimes tailored to your own OS or system config.

**Comment by DYL-WF** [comment]
I took the node modules out of the commit tho?

**Review by AvinashSingh786 — APPROVED** [review]
Oh I didn't see that.

**Pull request merged**
