### PR TITLE
Updated Login/Register pages

### PR DESCRIPTION
**Pull request by jademichellepeche**
Updated the UI. 
Still need to do validation.

### CODE REVIEW

**Review by DYL-WF — APPROVED** [review]

**Comment by DYL-WF** [comment]
We also need to make accommodations for the other user types (employee and owner)

There will need to be an insert post request for each kind of user. the login also need to check for that cause we have a seperate table for each user. My login api call only checks for the normal user table

**Review by RyanBroemer — COMMENTED** [review]
Looks good

**Comment by RyanBroemer** [comment]
Will look into API request once the TypeORM entities are sorted.

**Comment by jademichellepeche** [comment]
> 

Okay no problem. I will add that functionality.

**Pull request merged**
