### PR TITLE
🍱 adding Entity

### PR DESCRIPTION
**Pull request by RyanBroemer**
- adding badge entity

### CODE REVIEW

**Comment by RyanBroemer** [comment]
- Adding the badge_owned entity

**Comment by RyanBroemer** [comment]
Adding badge_claim entity

**Review by DYL-WF — APPROVED** [review]

**Comment by DYL-WF** [comment]
@RyanBroemer  im storing the badges locally. Im gonna save a special kind of id to the Badge Icon field which will be used to construct the badge in future

**Comment by RyanBroemer** [comment]
Sounds good

**Pull request merged**
